### ISSUE TITLE
Path to v1

### ISSUE THREAD

**Issue by chris-feist** [JetClosing/serverless-plugin-ignitor#2]
- [x] Add default config options for "invoke on deploy" and ignitor rate
- [x] Schedule option should be made more flexible to allow custom schedules + rates
- [x] Per function overrides for invoke on deploy and ignitor rate
- [x] Terminal/Console warning when no matches
- [x] unit tests for index.js
- [x] add `serverless-plugin` keyword to package.json
- [x] add eslint 
- [x] Specify `aws` provider: https://serverless.com/framework/docs/providers/aws/guide/plugins#provider-specific-plugins
- [x] add npm badges to README: 
```markdown
![npm downloads total](https://img.shields.io/npm/dt/serverless-plugin-ignitor.svg) ![npm version](https://img.shields.io/npm/v/serverless-plugin-ignitor.svg) ![npm license](https://img.shields.io/npm/l/serverless-plugin-ignitor.svg)
```

**Comment by icarus-sullivan** [comment]
**Enabled**
Not a fan of the enabled flag, would rather keep it named `schedule`. We don't want to add a schedule if we don't need to, and the implication is we would generate one regardless of whether they wanted it or not. 

**Invoke On Deploy**
However the idea to add another configuration, such as `immediate: true` seems like a good idea. Right now we are immediately calling them for each one that has been configured. 

**Terminal/Console Warning**
Good idea, not sure its a blocker for a v1 release. 

**Unit tests**
Added some basic manual tests [here](https://github.com/JetClosing/serverless-plugin-ignitor/pulls)

**Serverless Plugin**
We already have `serverless` in the package.json, I added `plugin` [here](https://github.com/JetClosing/serverless-plugin-ignitor/pulls)

**Comment by chris-feist** [comment]
A single flag to disable the plugin makes it easy to turn off the plugin for different environments, like dev environments. Save that 🤑

A schedule option should allow custom configuration for the schedule. For ease of use, disable the schedule by assigning to `null`. It wouldn't make sense to have two option fields to control it. 

On the console warning, it seems easy and like it'd be a good experience to warn when there are no matching functions. It's 3 lines of code max.

We should have the `serverless-plugin` specific keyword in package.json for discoverability. For example: searching npm using keywords: https://www.npmjs.com/search?q=keywords%3Aserverless-plugin

**Comment by icarus-sullivan** [comment]
Added all the requests here, closing this ticket
